services:
  - type: web
    name: expense-category-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt && python -c \"import nltk; nltk.download('stopwords'); nltk.download('wordnet'); nltk.download('omw-1.4')\""
    startCommand: "cd src && python serve_model.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
